import streamlit as st
import requests


# --------------------------------------------------
# Page Configuration
# --------------------------------------------------

st.set_page_config(
    page_title="House Price Predictor",
    page_icon="🏠",
    layout="wide"
)


# --------------------------------------------------
# API Configuration
# --------------------------------------------------

API_URL = "http://127.0.0.1:8000/predict"


# --------------------------------------------------
# Header
# --------------------------------------------------

st.title("🏠 House Price Prediction")
st.markdown(
    """
    ### Machine Learning Prediction Application

    Enter the characteristics of a house below to estimate its
    market price using a trained **Gradient Boosting Regression model**.
    """
)

st.divider()


# --------------------------------------------------
# Input Form
# --------------------------------------------------

st.subheader("🏡 Property Information")

with st.form("prediction_form"):

    col1, col2, col3 = st.columns(3)

    with col1:
        area = st.number_input(
            "Area (square feet)",
            min_value=100,
            max_value=50000,
            value=3000,
            step=100
        )

        bedrooms = st.number_input(
            "Bedrooms",
            min_value=1,
            max_value=10,
            value=3,
            step=1
        )

        bathrooms = st.number_input(
            "Bathrooms",
            min_value=1,
            max_value=10,
            value=2,
            step=1
        )

        stories = st.number_input(
            "Stories",
            min_value=1,
            max_value=10,
            value=2,
            step=1
        )

    with col2:
        mainroad = st.selectbox(
            "Main Road",
            ["yes", "no"]
        )

        guestroom = st.selectbox(
            "Guest Room",
            ["yes", "no"]
        )

        basement = st.selectbox(
            "Basement",
            ["yes", "no"]
        )

        hotwaterheating = st.selectbox(
            "Hot Water Heating",
            ["yes", "no"]
        )

    with col3:
        airconditioning = st.selectbox(
            "Air Conditioning",
            ["yes", "no"]
        )

        parking = st.number_input(
            "Parking Spaces",
            min_value=0,
            max_value=10,
            value=1,
            step=1
        )

        prefarea = st.selectbox(
            "Preferred Area",
            ["yes", "no"]
        )

        furnishingstatus = st.selectbox(
            "Furnishing Status",
            ["furnished", "semi-furnished", "unfurnished"]
        )

    st.divider()

    submitted = st.form_submit_button(
        "🔮 Predict House Price",
        use_container_width=True
    )


# --------------------------------------------------
# Prediction
# --------------------------------------------------

if submitted:

    input_data = {
        "area": area,
        "bedrooms": bedrooms,
        "bathrooms": bathrooms,
        "stories": stories,
        "mainroad": mainroad,
        "guestroom": guestroom,
        "basement": basement,
        "hotwaterheating": hotwaterheating,
        "airconditioning": airconditioning,
        "parking": parking,
        "prefarea": prefarea,
        "furnishingstatus": furnishingstatus
    }

    try:

        response = requests.post(
            API_URL,
            json=input_data,
            timeout=10
        )

        if response.status_code == 200:

            result = response.json()

            predicted_price = result["predicted_price"]

            st.success("Prediction generated successfully!")

            st.metric(
                label="Estimated House Price",
                value=f"KSh {predicted_price:,.2f}"
            )

            st.info(
                "The prediction was generated by the deployed "
                "Gradient Boosting Regression model through the FastAPI endpoint."
            )

        else:

            st.error(
                f"API request failed with status code "
                f"{response.status_code}"
            )

    except requests.exceptions.ConnectionError:

        st.error(
            "Could not connect to the prediction API. "
            "Make sure FastAPI is running on port 8000."
        )

    except requests.exceptions.Timeout:

        st.error(
            "The API request timed out. Please try again."
        )

    except Exception as e:

        st.error(
            f"An unexpected error occurred: {e}"
        )


# --------------------------------------------------
# Model Information
# --------------------------------------------------

st.divider()

st.subheader("📊 Model Information")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Model", "Gradient Boosting")

with col2:
    st.metric("R² Score", "0.6658")

with col3:
    st.metric("Features", "12")